/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import javax.swing.ImageIcon;

/**
 *
 * @author EMA
 */
public class frmInstrucciones extends javax.swing.JFrame {

    /**
     * Creates new form frmInstrucciones
     */
    ImageIcon instruccion1 = new ImageIcon("src/images/instruccion1.png");
    int posicionInstruccion = 1;
    
    
    public frmInstrucciones() {
        initComponents();
        lblInstruccion.setIcon(instruccion1);
        btnAnterior.setFocusable(false);
        btnSiguiente.setFocusable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblInstruccion = new javax.swing.JLabel();
        btnSiguiente = new javax.swing.JButton();
        btnAnterior = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        btnSiguiente.setText("Siguiente");
        btnSiguiente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSiguienteActionPerformed(evt);
            }
        });

        btnAnterior.setText("Anterior");
        btnAnterior.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAnteriorActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblInstruccion, javax.swing.GroupLayout.DEFAULT_SIZE, 680, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnAnterior)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnSiguiente)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(lblInstruccion, javax.swing.GroupLayout.PREFERRED_SIZE, 520, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSiguiente)
                    .addComponent(btnAnterior))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSiguienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSiguienteActionPerformed
        // TODO add your handling code here:
        posicionInstruccion++;
        switch(posicionInstruccion)
        {
            case 2:
                ImageIcon instruccion2 = new ImageIcon("src/images/instruccion2.png");
                lblInstruccion.setIcon(instruccion2);
                
                btnAnterior.setEnabled(true);
                break;
            case 3:
                ImageIcon instruccion3 = new ImageIcon("src/images/instruccion3.png");
                lblInstruccion.setIcon(instruccion3);
                
                break;
            case 4:
                ImageIcon instruccion4 = new ImageIcon("src/images/instruccion4.png");
                lblInstruccion.setIcon(instruccion4);
                
                break;
            case 5:
                ImageIcon instruccion5 = new ImageIcon("src/images/instruccion5.png");
                lblInstruccion.setIcon(instruccion5);
                break;
            case 6:
                ImageIcon instruccion6 = new ImageIcon("src/images/instruccion6.png");
                lblInstruccion.setIcon(instruccion6);
                btnSiguiente.setEnabled(false);
                break;
        }
    }//GEN-LAST:event_btnSiguienteActionPerformed

    private void btnAnteriorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAnteriorActionPerformed
        // TODO add your handling code here:
        posicionInstruccion--;
        switch(posicionInstruccion)
        {
            case 1:
                ImageIcon instruccion1 = new ImageIcon("src/images/instruccion1.png");
                lblInstruccion.setIcon(instruccion1);
                btnAnterior.setEnabled(false);
                break;
            case 2:
                ImageIcon instruccion2 = new ImageIcon("src/images/instruccion2.png");
                lblInstruccion.setIcon(instruccion2);
                
                
                break;
            case 3:
                ImageIcon instruccion3 = new ImageIcon("src/images/instruccion3.png");
                lblInstruccion.setIcon(instruccion3);
                
                break;
             case 4:
                ImageIcon instruccion4 = new ImageIcon("src/images/instruccion4.png");
                lblInstruccion.setIcon(instruccion4);
                break;
             case 5:
                ImageIcon instruccion5 = new ImageIcon("src/images/instruccion5.png");
                lblInstruccion.setIcon(instruccion5);
                btnSiguiente.setEnabled(true);
                break;
        }
    }//GEN-LAST:event_btnAnteriorActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmInstrucciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmInstrucciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmInstrucciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmInstrucciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmInstrucciones().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAnterior;
    private javax.swing.JButton btnSiguiente;
    private javax.swing.JLabel lblInstruccion;
    // End of variables declaration//GEN-END:variables
}
