/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import javax.swing.ImageIcon;

/**
 *
 * @author EMA
 */
public class PantallaPrincipal extends javax.swing.JFrame {

    // Import ImageIcon     
    ImageIcon pared = new ImageIcon("src/images/pared.png");
    ImageIcon no_pared = new ImageIcon("src/images/no_pared.png");
    ImageIcon bola_roja = new ImageIcon("src/images/bola_roja.png");
    ImageIcon bola_naranja = new ImageIcon("src/images/bola_naranja.png");
    ImageIcon bola_azul = new ImageIcon("src/images/bola_azul.png");
    ImageIcon bola_amarilla = new ImageIcon("src/images/bola_amarilla.png");
    ImageIcon flecha_izq = new ImageIcon("src/images/flecha_izq.png");
    ImageIcon flecha_der = new ImageIcon("src/images/flecha_der.png");

    int[][] Matriz = {{9,9,0,9},{1,2,3,4},{1,2,3,4},{1,2,3,4},{1,2,3,4}};
    
    public PantallaPrincipal() {
        initComponents();
        
        
        btnAL1.setIcon(flecha_izq);
        btnAL1.setFocusable(false);
        btnAL2.setIcon(flecha_izq);
        btnAL2.setFocusable(false);
        btnAL3.setIcon(flecha_izq);
        btnAL3.setFocusable(false);
        btnAL4.setIcon(flecha_izq);
        btnAL4.setFocusable(false);
        btnAL5.setIcon(flecha_izq);
        btnAL5.setFocusable(false);
        
        btnAR1.setIcon(flecha_der);
        btnAR1.setFocusable(false);
        btnAR2.setIcon(flecha_der);
        btnAR2.setFocusable(false);
        btnAR3.setIcon(flecha_der);
        btnAR3.setFocusable(false);
        btnAR4.setIcon(flecha_der);
        btnAR4.setFocusable(false);
        btnAR5.setIcon(flecha_der);
        btnAR5.setFocusable(false);
        
        lblA11.setIcon(pared);
        lblA12.setIcon(pared);
        lblA13.setIcon(no_pared);
        lblA14.setIcon(pared);
        lblA21.setIcon(bola_roja);
        lblA22.setIcon(bola_naranja);
        lblA23.setIcon(bola_azul);
        lblA24.setIcon(bola_amarilla);
        lblA31.setIcon(bola_roja);
        lblA32.setIcon(bola_naranja);
        lblA33.setIcon(bola_azul);
        lblA34.setIcon(bola_amarilla);
        lblA41.setIcon(bola_roja);
        lblA42.setIcon(bola_naranja);
        lblA43.setIcon(bola_azul);
        lblA44.setIcon(bola_amarilla);
        lblA51.setIcon(bola_roja);
        lblA52.setIcon(bola_naranja);
        lblA53.setIcon(bola_azul);
        lblA54.setIcon(bola_amarilla);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        lblA12 = new javax.swing.JLabel();
        lblA11 = new javax.swing.JLabel();
        lblA14 = new javax.swing.JLabel();
        lblA13 = new javax.swing.JLabel();
        lblA21 = new javax.swing.JLabel();
        lblA22 = new javax.swing.JLabel();
        lblA23 = new javax.swing.JLabel();
        lblA24 = new javax.swing.JLabel();
        lblA34 = new javax.swing.JLabel();
        lblA33 = new javax.swing.JLabel();
        lblA32 = new javax.swing.JLabel();
        lblA31 = new javax.swing.JLabel();
        lblA44 = new javax.swing.JLabel();
        lblA43 = new javax.swing.JLabel();
        lblA42 = new javax.swing.JLabel();
        lblA41 = new javax.swing.JLabel();
        lblA51 = new javax.swing.JLabel();
        lblA52 = new javax.swing.JLabel();
        lblA53 = new javax.swing.JLabel();
        lblA54 = new javax.swing.JLabel();
        btnAL1 = new javax.swing.JButton();
        btnAL2 = new javax.swing.JButton();
        btnAL3 = new javax.swing.JButton();
        btnAL4 = new javax.swing.JButton();
        btnAL5 = new javax.swing.JButton();
        btnAR1 = new javax.swing.JButton();
        btnAR2 = new javax.swing.JButton();
        btnAR3 = new javax.swing.JButton();
        btnAR4 = new javax.swing.JButton();
        btnAR5 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton1.setText("Cargar Archivo...");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Cargar Archivo...");

        btnAL1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAL1ActionPerformed(evt);
            }
        });

        btnAL2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAL2ActionPerformed(evt);
            }
        });

        btnAL3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAL3ActionPerformed(evt);
            }
        });

        btnAL4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAL4ActionPerformed(evt);
            }
        });

        btnAL5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAL5ActionPerformed(evt);
            }
        });

        btnAR1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAR1ActionPerformed(evt);
            }
        });

        btnAR2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAR2ActionPerformed(evt);
            }
        });

        btnAR3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAR3ActionPerformed(evt);
            }
        });

        btnAR4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAR4ActionPerformed(evt);
            }
        });

        btnAR5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAR5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(83, 83, 83)
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 265, Short.MAX_VALUE)
                .addComponent(jButton2)
                .addGap(106, 106, 106))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnAL1, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAL2, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAL3, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAL4, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAL5, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lblA51, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblA52, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblA53, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblA54, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnAR5, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lblA41, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblA42, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblA43, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblA44, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnAR4, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(lblA31, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblA32, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblA33, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblA34, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(lblA21, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(lblA22, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(lblA23, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(lblA24, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(lblA11, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(lblA12, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(lblA13, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(lblA14, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnAR1, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnAR2, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnAR3, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnAR5, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton1)
                            .addComponent(jButton2))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                    .addComponent(btnAL1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                        .addComponent(lblA12, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addComponent(lblA11, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
                                                        .addComponent(lblA14, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
                                                        .addComponent(lblA13, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE))
                                                    .addComponent(btnAR1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(lblA22, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(lblA21, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(lblA24, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(lblA23, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(btnAL2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                            .addComponent(btnAR2, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(lblA32, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(lblA31, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(lblA34, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(lblA33, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(btnAR3, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addComponent(btnAL3, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lblA42, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblA41, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblA44, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblA43, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnAR4, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(btnAL4, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblA52, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblA51, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblA54, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblA53, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnAL5, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(140, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnAR1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAR1ActionPerformed
        // TODO add your handling code here:
        
        moverDerecha(0);
        imprimir_resultado();
        
       
        
        
        
    }//GEN-LAST:event_btnAR1ActionPerformed

    private void btnAR2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAR2ActionPerformed
        // TODO add your handling code here:
         moverDerecha(1);
        imprimir_resultado();
       
    }//GEN-LAST:event_btnAR2ActionPerformed

    private void btnAR3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAR3ActionPerformed
        // TODO add your handling code here:
         moverDerecha(2);
        imprimir_resultado();
        
        
    }//GEN-LAST:event_btnAR3ActionPerformed

    private void btnAR4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAR4ActionPerformed
        // TODO add your handling code here:
         moverDerecha(3);
        imprimir_resultado();        
    }//GEN-LAST:event_btnAR4ActionPerformed

    private void btnAR5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAR5ActionPerformed
        // TODO add your handling code here:
         moverDerecha(4);
        imprimir_resultado();
    }//GEN-LAST:event_btnAR5ActionPerformed

    private void btnAL1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAL1ActionPerformed
        // TODO add your handling code here:
        moverIzquierda(0);
        imprimir_resultado();
    }//GEN-LAST:event_btnAL1ActionPerformed

    private void btnAL2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAL2ActionPerformed
        // TODO add your handling code here:
        moverIzquierda(1);
        imprimir_resultado();
    }//GEN-LAST:event_btnAL2ActionPerformed

    private void btnAL3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAL3ActionPerformed
        // TODO add your handling code here:
        moverIzquierda(2);
        imprimir_resultado();
    }//GEN-LAST:event_btnAL3ActionPerformed

    private void btnAL4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAL4ActionPerformed
        // TODO add your handling code here:
        moverIzquierda(3);
        imprimir_resultado();
    }//GEN-LAST:event_btnAL4ActionPerformed

    private void btnAL5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAL5ActionPerformed
        // TODO add your handling code here:
        moverIzquierda(4);
        imprimir_resultado();
    }//GEN-LAST:event_btnAL5ActionPerformed

    public void imprimir_resultado()
    {
        for (int i = 0; i < 5; i++) {
            for (int j = 0; j < 4; j++) {
                System.out.print(Matriz[i][j]);
            }
            System.out.print("\n");
                    
        }
        System.out.print("\n");
    }
    
    public void moverDerecha(int pPos)
    {
        int espacio1 = Matriz[pPos][0];
        int espacio2 = Matriz[pPos][1];
        int espacio3 = Matriz[pPos][2];
        int espacio4 = Matriz[pPos][3];
        
        Matriz[pPos][0] = espacio4;
        Matriz[pPos][1] = espacio1;
        Matriz[pPos][2] = espacio2;
        Matriz[pPos][3] = espacio3;
        
        actualizar_interfaz(pPos);
        
    }
    
    public void moverIzquierda(int pPos)
    {
        int espacio1 = Matriz[pPos][0];
        int espacio2 = Matriz[pPos][1];
        int espacio3 = Matriz[pPos][2];
        int espacio4 = Matriz[pPos][3];
        
        Matriz[pPos][0] = espacio2;
        Matriz[pPos][1] = espacio3;
        Matriz[pPos][2] = espacio4;
        Matriz[pPos][3] = espacio1;
        
        actualizar_interfaz(pPos);
    }
    
    public void seleccionar_imagen_columna_1(int pPos,ImageIcon image)
    {
        switch(pPos)
        {
            case 0:
                lblA11.setIcon(image);
                break;
            case 1:
                lblA21.setIcon(image);
                break;
            case 2:
                lblA31.setIcon(image);
                break;
            case 3:
                lblA41.setIcon(image);
                break;
            case 4:
                lblA51.setIcon(image);
                break;
        }
    }
    
    public void actualizar_interfaz(int pPos)
    {
        //For: check the row according position
        for(int i = 0; i<4;i++)
        {
            //Position i in the row
            switch(i)
            {
                case 0:
                    switch(Matriz[pPos][0])
                    {
                        case 0:
                            seleccionar_imagen_columna_1(pPos, no_pared);
                            break;
                        case 9:
                            seleccionar_imagen_columna_1(pPos, pared);
                            break;
                        case 1:
                            seleccionar_imagen_columna_1(pPos, bola_roja);
                            break;
                        case 2:
                            seleccionar_imagen_columna_1(pPos, bola_naranja);
                            break;
                        case 3:
                            seleccionar_imagen_columna_1(pPos, bola_azul);
                            break;
                        case 4:
                            seleccionar_imagen_columna_1(pPos, bola_amarilla);
                            break;
                    }
                    
                    break;
                    
                    case 1:
                        switch(Matriz[pPos][1])
                        {
                            case 0:
                                seleccionar_imagen_columna_2(pPos, no_pared);
                                break;
                            case 9:
                                seleccionar_imagen_columna_2(pPos, pared);
                                break;
                            case 1:
                                seleccionar_imagen_columna_2(pPos, bola_roja);
                                break;
                            case 2:
                                seleccionar_imagen_columna_2(pPos, bola_naranja);
                                break;
                            case 3:
                                seleccionar_imagen_columna_2(pPos, bola_azul);
                                break;
                            case 4:
                                seleccionar_imagen_columna_2(pPos, bola_amarilla);
                                break;
                        }
                    
                    break;
                        
                    case 2:
                        switch(Matriz[pPos][2])
                        {
                             case 0:
                                seleccionar_imagen_columna_3(pPos, no_pared);
                                break;
                            case 9:
                                seleccionar_imagen_columna_3(pPos, pared);
                                break;
                            case 1:
                                seleccionar_imagen_columna_3(pPos, bola_roja);
                                break;
                            case 2:
                                seleccionar_imagen_columna_3(pPos, bola_naranja);
                                break;
                            case 3:
                                seleccionar_imagen_columna_3(pPos, bola_azul);
                                break;
                            case 4:
                                seleccionar_imagen_columna_3(pPos, bola_amarilla);
                                break;
                        }
                    
                    break;
                        
                        
                    case 3:
                        switch(Matriz[pPos][3])
                        {
                             case 0:
                                    seleccionar_imagen_columna_4(pPos, no_pared);
                                    break;
                                case 9:
                                    seleccionar_imagen_columna_4(pPos, pared);
                                    break;
                                case 1:
                                    seleccionar_imagen_columna_4(pPos, bola_roja);
                                    break;
                                case 2:
                                    seleccionar_imagen_columna_4(pPos, bola_naranja);
                                    break;
                                case 3:
                                    seleccionar_imagen_columna_4(pPos, bola_azul);
                                    break;
                                case 4:
                                    seleccionar_imagen_columna_4(pPos, bola_amarilla);
                                    break;
                        }
                    
                    break;
            }
        }
    }
    
    public void seleccionar_imagen_columna_2(int pPos,ImageIcon image)
    {
        switch(pPos)
        {
            case 0:
                lblA12.setIcon(image);
                break;
            case 1:
                lblA22.setIcon(image);
                break;
            case 2:
                lblA32.setIcon(image);
                break;
            case 3:
                lblA42.setIcon(image);
                break;
            case 4:
                lblA52.setIcon(image);
                break;
        }
    }
    
    public void seleccionar_imagen_columna_3(int pPos,ImageIcon image)
    {
        switch(pPos)
        {
            case 0:
                lblA13.setIcon(image);
                break;
            case 1:
                lblA23.setIcon(image);
                break;
            case 2:
                lblA33.setIcon(image);
                break;
            case 3:
                lblA43.setIcon(image);
                break;
            case 4:
                lblA53.setIcon(image);
                break;
        }
    }
    
    public void seleccionar_imagen_columna_4(int pPos,ImageIcon image)
    {
        switch(pPos)
        {
            case 0:
                lblA14.setIcon(image);
                break;
            case 1:
                lblA24.setIcon(image);
                break;
            case 2:
                lblA34.setIcon(image);
                break;
            case 3:
                lblA44.setIcon(image);
                break;
            case 4:
                lblA54.setIcon(image);
                break;
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PantallaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PantallaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PantallaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PantallaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PantallaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAL1;
    private javax.swing.JButton btnAL2;
    private javax.swing.JButton btnAL3;
    private javax.swing.JButton btnAL4;
    private javax.swing.JButton btnAL5;
    private javax.swing.JButton btnAR1;
    private javax.swing.JButton btnAR2;
    private javax.swing.JButton btnAR3;
    private javax.swing.JButton btnAR4;
    private javax.swing.JButton btnAR5;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblA11;
    private javax.swing.JLabel lblA12;
    private javax.swing.JLabel lblA13;
    private javax.swing.JLabel lblA14;
    private javax.swing.JLabel lblA21;
    private javax.swing.JLabel lblA22;
    private javax.swing.JLabel lblA23;
    private javax.swing.JLabel lblA24;
    private javax.swing.JLabel lblA31;
    private javax.swing.JLabel lblA32;
    private javax.swing.JLabel lblA33;
    private javax.swing.JLabel lblA34;
    private javax.swing.JLabel lblA41;
    private javax.swing.JLabel lblA42;
    private javax.swing.JLabel lblA43;
    private javax.swing.JLabel lblA44;
    private javax.swing.JLabel lblA51;
    private javax.swing.JLabel lblA52;
    private javax.swing.JLabel lblA53;
    private javax.swing.JLabel lblA54;
    // End of variables declaration//GEN-END:variables
}
